language: node_js
sudo: false
node_js:
  - stable
addons:
  firefox: '42.0'

before_script:
  - npm install web-component-tester
  - npm install bower
  - bower install
  - npm install polylint
  - polylint
  - export PATH=$PWD/node_modules/.bin:$PATH

script:
  - xvfb-run wct
  - bash ./gpages_build.sh ronnyroeller paper-alert-dialog "Ronny Roeller" ronny@collaborne.com
